[package]
name = "lib_bolt"
version = "0.11.3"
edition = "2021"

[dependencies]
actix-web = "4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
actix-files = "0.6.2"
webbrowser = "0.8.3"
dirs = "4.0.0"
reqwest = { version = "0.11.14", features = ["blocking", "json"] }